apiVersion: v1
data:
  tls.crt: ***REMOVED***
  tls.key: ***REMOVED***
kind: Secret
metadata:
  annotations:
    "pulumi.com/patchForce": "true"
    replicator.v1.mittwald.de/replicate-to-matching: needs-workspace-tls=true
  creationTimestamp: null
  name: workspace-wildcard
type: kubernetes.io/tls
