name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - run: |
          gcloud builds submit \
              --quiet \
              --region=global \
              --timeout=15m \
              --tag "gcr.io/***REMOVED***/github.com/pachyderm/helium" .

      - name: Pull Versionbump
        run: |
            mkdir -p $GITHUB_WORKSPACE/bin
            wget -O $GITHUB_WORKSPACE/bin/version-bump https://github.com/pachyderm/version-bump/releases/download/v0.0.3/version-bump-amd64-v0.0.3
            chmod a+x $GITHUB_WORKSPACE/bin/version-bump 
            echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Update cluster config repo
        run: |
          HELIUM_DOCKER_IMAGE_DIGEST=$(gcloud container images describe gcr.io/***REMOVED***/github.com/pachyderm/helium:latest --format="value(image_summary.fully_qualified_digest)")
          echo $HELIUM_DOCKER_IMAGE_DIGEST
          version-bump --owner=pachyderm --repo=cluster-config --file=argocd/workloads/production/helium/deployment.yaml --branch=master --location=spec.template.spec.containers.[name=helium].image --replacement=$HELIUM_DOCKER_IMAGE_DIGEST --author-name=***REMOVED*** --author-email=buildbot@***REMOVED*** --token=${{ secrets.GH_TOKEN }} --message="bump helium version"
          version-bump --owner=pachyderm --repo=cluster-config --file=argocd/workloads/production/helium/cp-deployment.yaml --branch=master --location=spec.template.spec.containers.[name=helium-cp].image --replacement=$HELIUM_DOCKER_IMAGE_DIGEST --author-name=***REMOVED*** --author-email=buildbot@***REMOVED*** --token=${{ secrets.GH_TOKEN }} --message="bump helium-cp version"

          