name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - run: |
          gcloud builds submit --region=global --tag gcr.io/***REMOVED***/github.com/pachyderm/helium .
      
      - run: |
          HELIUM_DOCKER_IMAGE_DIGEST=$(gcloud container images describe gcr.io/***REMOVED***/github.com/pachyderm/helium:$env:GITHUB_SHA --format="value(image_summary.fully_qualified_digest)")

      - run: |
          gh workflow run bump_helium_version.yml -f digest=$HELIUM_DOCKER_IMAGE_DIGEST --repo pachyderm/cluster-config
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
